apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: minio
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: minio
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: minio
    spec:
      containers:
        - args:
            - server
            - --address
            - 0.0.0.0:9000
            - --console-address
            - 0.0.0.0:32765
            - /tmp
          env:
            - name: MINIO_ROOT_PASSWORD
              value: 9e1c40c65a615a5b52f52aeeaf549944ec53acb1dff4a0bf01fb58e969f915c8
            - name: MINIO_ROOT_USER
              value: 5a7bdb5f42c41e0622bf61d6e08d5537
          image: minio
          name: hasura-storage-minio
          ports:
            - containerPort: 9000
            - containerPort: 32765
          resources: {}
      restartPolicy: Always
status: {}
