apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: storage
  name: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: storage
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: storage
    spec:
      containers:
        - args:
            - serve
          env:
            - name: DEBUG
              value: "true"
            - name: HASURA_ENDPOINT
              value: http://graphql-engine:8080/v1
            - name: HASURA_GRAPHQL_ADMIN_SECRET
              value: hello123
            - name: HASURA_METADATA
              value: "1"
            - name: POSTGRES_MIGRATIONS
              value: "1"
            - name: POSTGRES_MIGRATIONS_SOURCE
              value: postgres://postgres:hejsan@postgres:5432/postgres?sslmode=disable
            - name: S3_ACCESS_KEY
              value: 5a7bdb5f42c41e0622bf61d6e08d5537
            - name: S3_BUCKET
              value: default
            - name: S3_ENDPOINT
              value: http://minio:9000
            - name: S3_ROOT_FOLDER
              value: f215cf48-7458-4596-9aa5-2159fc6a3caf
            - name: S3_SECRET_KEY
              value: 9e1c40c65a615a5b52f52aeeaf549944ec53acb1dff4a0bf01fb58e969f915c8
          image: hasura-storage:dev
          name: hasura-storage-storage
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
status: {}
